### ISSUE TITLE
PPT 보안 제출

### ISSUE THREAD

**Issue by antonio26548** [tukcom2023CD/MBTI#1]
QR코드에 관련된 추가적인 기능
음성 인식에 필요한 구체적인 방법 기술
PPT 수정 후 제출

**Comment by jisssuu** [comment]
1. 11페이지 3번 이용 범위 확대 모든 상품 => 우유, 라면, 과자로 범위를 줄임

**Comment by jisssuu** [comment]
2. 업무 변경으로 인해 , 업무 분담 페이지 변경

**Comment by jisssuu** [comment]
3. DB 관련   상품 http://www.allproductkorea.or.kr/products/database/inquiry
