### ISSUE TITLE
button을 눌러서 카메라 화면 보여주기 issue

### ISSUE THREAD

**Issue by jisssuu** [tukcom2023CD/MBTI#5]
QR 리더기를 버튼을 누를 시 보여주는 화면을 구성하는 도중,
 Thread 1: "-[UIViewController QR:]: unrecognized selector sent to instance 0x147d0bfa0" 오류가 지속적으로 발생
발생이 되면서 앱 실행이 멈추는 오류가 발생

**Comment by antonio26548** [comment]
오류를 검색해보니 버튼의 연결이 중복되거나 잘못 연결되는 경우 발생되는 것으로
버튼의 연결을 해제 , @IBAction 를 다시 작성 했으나 해결이 안됨

버튼을 삭제하고 다시 작성 후 해당 이슈 해결
